"""
Live File Monitor Module

Monitors important user folders while
ASTRA-AI is running and synchronizes
file changes with the SQLite database.

Supported events:

- File created
- File deleted
- File modified
- File renamed
- File moved
- Folder deleted
- Folder renamed
- Folder moved

Filtering is handled by FileFilter.

ASTRA-AI V1
"""

import time
import threading

from pathlib import Path
from datetime import datetime

from watchdog.observers import Observer
from watchdog.events import (
    FileSystemEventHandler
)

from automation.file_filter import FileFilter
from database.database_manager import DatabaseManager


class FileMonitorHandler(FileSystemEventHandler):
    """
    Handle live file system events and
    synchronize valid files with SQLite.

    Watchdog callbacks run in a background
    thread, so all database operations are
    protected with a lock.
    """

    def __init__(
        self,
        database,
        database_lock
    ):

        super().__init__()

        self.database = database

        self.database_lock = database_lock

        # ----------------------------------
        # Prevent duplicate rapid events
        # generated by Windows.
        # ----------------------------------

        self.recent_events = {}

        self.event_cooldown = 0.5

        self.event_lock = threading.Lock()

    # --------------------------------------------------
    # Event Deduplication
    # --------------------------------------------------

    def is_duplicate_event(
        self,
        event_type,
        path
    ):
        """
        Prevent processing the same event
        repeatedly within a short time.
        """

        key = (
            event_type,
            str(path).lower()
        )

        current_time = time.time()

        with self.event_lock:

            previous_time = self.recent_events.get(
                key
            )

            if previous_time is not None:

                if (
                    current_time - previous_time
                    < self.event_cooldown
                ):

                    return True

            self.recent_events[key] = current_time

            # ----------------------------------
            # Prevent unlimited memory growth
            # ----------------------------------

            if len(self.recent_events) > 1000:

                cutoff = (
                    current_time - 10
                )

                self.recent_events = {

                    event_key: timestamp

                    for event_key, timestamp
                    in self.recent_events.items()

                    if timestamp >= cutoff

                }

        return False

    # --------------------------------------------------
    # Normalize Path
    # --------------------------------------------------

    @staticmethod
    def normalize_path(path):
        """
        Return normalized absolute path.
        """

        try:

            return str(
                Path(path).resolve()
            )

        except Exception:

            return str(path)

    # --------------------------------------------------
    # Check Valid File
    # --------------------------------------------------

    @staticmethod
    def is_valid_file(path):
        """
        Check whether a file should be
        stored inside the ASTRA database.
        """

        try:

            return FileFilter.is_valid_file(
                path
            )

        except Exception:

            return False

    # --------------------------------------------------
    # Database File Exists
    # --------------------------------------------------

    def database_file_exists(
        self,
        file_path
    ):
        """
        Thread-safe database file check.
        """

        with self.database_lock:

            return self.database.file_exists(
                file_path
            )

    # --------------------------------------------------
    # Database Delete File
    # --------------------------------------------------

    def database_delete_file(
        self,
        file_path
    ):
        """
        Thread-safe database file removal.
        """

        with self.database_lock:

            return self.database.delete_file(
                file_path
            )

    # --------------------------------------------------
    # Add / Refresh File
    # --------------------------------------------------

    def sync_file(
        self,
        file_path
    ):
        """
        Add a new file or refresh an
        existing file entry.
        """

        try:

            file_path = self.normalize_path(
                file_path
            )

            path = Path(file_path)

            # ----------------------------------
            # File may disappear before the
            # watchdog event is processed.
            # ----------------------------------

            if not path.exists():

                return False

            if not path.is_file():

                return False

            # ----------------------------------
            # Apply ASTRA File Filter
            # ----------------------------------

            if not self.is_valid_file(
                file_path
            ):

                # If the file was previously
                # indexed but is no longer valid,
                # remove it.

                if self.database_file_exists(
                    file_path
                ):

                    self.database_delete_file(
                        file_path
                    )

                return False

            file_size = path.stat().st_size

            last_modified = (
                datetime.fromtimestamp(
                    path.stat().st_mtime
                ).isoformat()
            )

            # ----------------------------------
            # Insert / Update Database
            # ----------------------------------

            with self.database_lock:

                success = self.database.insert_file(

                    name=path.stem,

                    extension=path.suffix,

                    full_path=file_path,

                    file_size=file_size,

                    last_modified=last_modified,

                    commit=True

                )

            if success:

                print(
                    f"[File Monitor] Synced : "
                    f"{file_path}"
                )

            return success

        except FileNotFoundError:

            return False

        except PermissionError:

            return False

        except OSError:

            return False

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Sync Error : {error}"
            )

            return False

    # --------------------------------------------------
    # Remove File
    # --------------------------------------------------

    def remove_file(
        self,
        file_path
    ):
        """
        Remove a deleted file from
        the SQLite database.
        """

        try:

            file_path = self.normalize_path(
                file_path
            )

            if not self.database_file_exists(
                file_path
            ):

                return False

            success = self.database_delete_file(
                file_path
            )

            if success:

                print(
                    f"[File Monitor] Removed : "
                    f"{file_path}"
                )

            return success

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Remove Error : {error}"
            )

            return False

    # --------------------------------------------------
    # Remove Directory Files
    # --------------------------------------------------

    def remove_directory_files(
        self,
        directory_path
    ):
        """
        Remove all indexed files that
        belong to a deleted directory.
        """

        try:

            directory_path = self.normalize_path(
                directory_path
            )

            directory_path = (
                directory_path
                .rstrip("\\/")
                .lower()
            )

            with self.database_lock:

                files = self.database.get_all_files()

            removed_count = 0

            for _, _, full_path in files:

                normalized_file = (
                    self.normalize_path(
                        full_path
                    ).lower()
                )

                if (

                    normalized_file.startswith(
                        directory_path + "\\"
                    )

                    or

                    normalized_file.startswith(
                        directory_path + "/"
                    )

                ):

                    if self.database_delete_file(
                        full_path
                    ):

                        removed_count += 1

            if removed_count > 0:

                print(
                    f"[File Monitor] "
                    f"Removed {removed_count} "
                    f"files from directory : "
                    f"{directory_path}"
                )

            return removed_count

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Directory Remove Error : "
                f"{error}"
            )

            return 0

    # --------------------------------------------------
    # Update Moved File
    # --------------------------------------------------

    def move_file(
        self,
        old_path,
        new_path
    ):
        """
        Synchronize a renamed or moved file.
        """

        try:

            old_path = self.normalize_path(
                old_path
            )

            new_path = self.normalize_path(
                new_path
            )

            old_exists = self.database_file_exists(
                old_path
            )

            new_file = Path(new_path)

            # ----------------------------------
            # New file may not be valid for
            # ASTRA indexing.
            # ----------------------------------

            if not self.is_valid_file(
                new_path
            ):

                if old_exists:

                    self.database_delete_file(
                        old_path
                    )

                    print(
                        f"[File Monitor] "
                        f"Removed after move : "
                        f"{old_path}"
                    )

                return False

            # ----------------------------------
            # Existing indexed file
            # ----------------------------------

            if old_exists:

                with self.database_lock:

                    success = (
                        self.database.update_file_name(

                            old_path=old_path,

                            new_name=new_file.stem,

                            new_path=new_path

                        )
                    )

                if success:

                    print(
                        f"[File Monitor] "
                        f"Moved :\n"
                        f"  From : {old_path}\n"
                        f"  To   : {new_path}"
                    )

                return success

            # ----------------------------------
            # Old file was not indexed
            # ----------------------------------

            return self.sync_file(
                new_path
            )

        except FileNotFoundError:

            self.remove_file(
                old_path
            )

            return False

        except PermissionError:

            return False

        except OSError:

            return False

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Move Error : {error}"
            )

            return False

    # --------------------------------------------------
    # Update Directory Move
    # --------------------------------------------------

    def move_directory(
        self,
        old_directory,
        new_directory
    ):
        """
        Update database paths when an
        entire folder is renamed or moved.
        """

        try:

            old_directory = self.normalize_path(
                old_directory
            ).rstrip("\\/")

            new_directory = self.normalize_path(
                new_directory
            ).rstrip("\\/")

            old_directory_lower = (
                old_directory.lower()
            )

            with self.database_lock:

                files = self.database.get_all_files()

            updated_count = 0

            for _, _, full_path in files:

                normalized_path = (
                    self.normalize_path(
                        full_path
                    )
                )

                normalized_lower = (
                    normalized_path.lower()
                )

                if not (

                    normalized_lower.startswith(
                        old_directory_lower + "\\"
                    )

                    or

                    normalized_lower.startswith(
                        old_directory_lower + "/"
                    )

                ):

                    continue

                try:

                    relative_path = Path(
                        normalized_path
                    ).relative_to(
                        Path(old_directory)
                    )

                except ValueError:

                    continue

                updated_path = str(

                    Path(new_directory) /
                    relative_path

                )

                if Path(updated_path).exists():

                    with self.database_lock:

                        success = (
                            self.database.update_file_path(

                                old_path=normalized_path,

                                new_path=updated_path

                            )
                        )

                    if success:

                        updated_count += 1

                else:

                    self.database_delete_file(
                        normalized_path
                    )

            print(
                f"[File Monitor] "
                f"Directory moved. "
                f"Updated files : "
                f"{updated_count}"
            )

            return updated_count

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Directory Move Error : "
                f"{error}"
            )

            return 0

    # --------------------------------------------------
    # File Created
    # --------------------------------------------------

    def on_created(self, event):

        if event.is_directory:

            return

        if self.is_duplicate_event(
            "created",
            event.src_path
        ):

            return

        self.sync_file(
            event.src_path
        )

    # --------------------------------------------------
    # File Deleted
    # --------------------------------------------------

    def on_deleted(self, event):

        if self.is_duplicate_event(
            "deleted",
            event.src_path
        ):

            return

        if event.is_directory:

            self.remove_directory_files(
                event.src_path
            )

            return

        self.remove_file(
            event.src_path
        )

    # --------------------------------------------------
    # File Modified
    # --------------------------------------------------

    def on_modified(self, event):

        if event.is_directory:

            return

        if self.is_duplicate_event(
            "modified",
            event.src_path
        ):

            return

        self.sync_file(
            event.src_path
        )

    # --------------------------------------------------
    # File Moved
    # --------------------------------------------------

    def on_moved(self, event):

        event_key = (

            f"{event.src_path}"
            f"->{event.dest_path}"

        )

        if self.is_duplicate_event(
            "moved",
            event_key
        ):

            return

        if event.is_directory:

            self.move_directory(

                old_directory=event.src_path,

                new_directory=event.dest_path

            )

            return

        self.move_file(

            old_path=event.src_path,

            new_path=event.dest_path

        )


class FileMonitor:
    """
    Monitor ASTRA indexed folders while
    the application is running.
    """

    def __init__(
        self,
        scan_folders=None
    ):

        # ----------------------------------
        # Database
        # ----------------------------------

        self.database = DatabaseManager()

        # ----------------------------------
        # Thread Synchronization
        # ----------------------------------

        self.database_lock = threading.RLock()

        # ----------------------------------
        # Watchdog
        # ----------------------------------

        self.observer = Observer()

        self.handler = FileMonitorHandler(

            self.database,

            self.database_lock

        )

        self.running = False

        # ----------------------------------
        # Scan Folders
        # ----------------------------------

        if scan_folders is None:

            self.scan_folders = (
                self.get_default_folders()
            )

        else:

            self.scan_folders = [

                Path(folder).resolve()

                for folder in scan_folders

                if Path(folder).exists()

            ]

    # --------------------------------------------------
    # Default Folders
    # --------------------------------------------------

    @staticmethod
    def get_default_folders():
        """
        Return the same important folders
        used by ASTRA FileIndexer.
        """

        home = Path.home()

        folders = [

            home / "Desktop",

            home / "Documents",

            home / "Downloads",

            home / "Pictures",

            home / "Videos",

            home / "Music"

        ]

        # ----------------------------------
        # Local Disk E
        # ----------------------------------

        e_drive = Path("E:/")

        if e_drive.exists():

            print(
                "[File Monitor] "
                "Detected Local Disk E"
            )

            folders.append(
                e_drive
            )

        # ----------------------------------
        # Keep Existing Folders
        # ----------------------------------

        folders = [

            folder.resolve()

            for folder in folders

            if folder.exists()

        ]

        # ----------------------------------
        # Remove Duplicates
        # ----------------------------------

        unique_folders = []

        visited = set()

        for folder in folders:

            if folder not in visited:

                visited.add(folder)

                unique_folders.append(folder)

        return unique_folders

    # --------------------------------------------------
    # Start Monitoring
    # --------------------------------------------------

    def start(self):
        """
        Start live file monitoring.
        """

        if self.running:

            print(
                "[File Monitor] "
                "Already running."
            )

            return

        if not self.scan_folders:

            print(
                "[File Monitor] "
                "No folders available."
            )

            return

        print(
            "\n=============================="
        )

        print(
            "ASTRA Live File Monitor"
        )

        print(
            "=============================="
        )

        scheduled_count = 0

        for folder in self.scan_folders:

            try:

                self.observer.schedule(

                    self.handler,

                    str(folder),

                    recursive=True

                )

                scheduled_count += 1

                print(
                    f"Monitoring : {folder}"
                )

            except Exception as error:

                print(
                    f"[File Monitor] "
                    f"Could not monitor "
                    f"{folder} : {error}"
                )

        if scheduled_count == 0:

            print(
                "[File Monitor] "
                "No folders could be monitored."
            )

            return

        try:

            self.observer.start()

            self.running = True

            print(
                "\nLive file monitoring started."
            )

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Start Error : {error}"
            )

    # --------------------------------------------------
    # Stop Monitoring
    # --------------------------------------------------

    def stop(self):
        """
        Stop live file monitoring safely.
        """

        if not self.running:

            return

        print(
            "\nStopping live file monitor..."
        )

        try:

            self.observer.stop()

            self.observer.join(
                timeout=5
            )

        except Exception as error:

            print(
                f"[File Monitor] "
                f"Stop Error : {error}"
            )

        finally:

            self.running = False

            print(
                "Live file monitor stopped."
            )

    # --------------------------------------------------
    # Close
    # --------------------------------------------------

    def close(self):
        """
        Stop monitor and close database.
        """

        self.stop()

        try:

            with self.database_lock:

                self.database.close()

        except Exception:

            pass